### PR TITLE
Fixed missed bug where large negative numbers are parsed incorrectly

### PR DESCRIPTION
**Pull request by RyanHarlich**

### CODE REVIEW

**Review by jonaspfab — CHANGES_REQUESTED** [review]
Looks good for the atoms. However, we will also need to update the chain letter for helices and sheets + we also need to update the write method in helix_refinement and merge_chains scripts.
Ideally we would encapsulate all mrc/pdb reading and writing in a wrapper class to only do this once. For now this is not necessary tho.

**Comment by RyanHarlich** [comment]
Hi Jonas,

It is good enough for the 50 proteins result table in the paper though right? For the two proteins that needed it; that is the matching Ca score and RMSD score.

Cheers,
Ryan Harlich



Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------

**Comment by jonaspfab** [comment]
Hi Ryan,

If it creates a result I guess it’s better than none. Did you check if it actually creates a correct PDB file with over 10,000 atoms?

Best,
Jonas

On Jul 27, 2019, at 2:06 PM, Ryan Harlich <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi Jonas,

It is good enough for the 50 proteins result table in the paper though right? For the two proteins that needed it; that is the matching Ca score and RMSD score.

Cheers,
Ryan Harlich



Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------

**Comment by jonaspfab** [comment]
I’m gonna merge it for now tho, but let’s keep it in mind.

On Jul 27, 2019, at 2:06 PM, Ryan Harlich <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi Jonas,

It is good enough for the 50 proteins result table in the paper though right? For the two proteins that needed it; that is the matching Ca score and RMSD score.

Cheers,
Ryan Harlich



Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------

**Comment by RyanHarlich** [comment]
Hi Jonas,

It creates over 10,000 in first walk. For the final prediction it was not over 10,000. I wasn't sure the process of the steps in between yet. It is on DAIS 5 folder TwoChain if you want to have a look (output2 is done output1 is in process). The results are better so I thought it would be good to put this in the table.

Best,
Ryan Harlich



Sent from my Verizon, Samsung Galaxy smartphone


-------- Original message --------

**Pull request merged**
